version: '3.7'
services:
  api:
    build: ./BugTracker
    environment:
      - ConnectionStrings__PgSql=Server=postgres; Port=5432; Database=dev; Username=developer_blue; Password=postgres123;
  website:
    build: ./Client
    restart: unless-stopped
    environment:
      PROXY_TO: http://api:5000/
    ports:
      - 3000:3000
  postgres:
    image: postgres:11.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:
